spring:
  redis:
    host: 192.168.207.130
    port: 6379
    password: 123456
    database: 0
    connect-timeout: 10000
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        min-idle: 5
        max-wait: -1
  elasticsearch:
    rest:
      uris: localhost:9200
logging:
  config: src/main/resources/log4j2-spring.xml